### PR TITLE
cirrus: Add CS35L41 firmware for Dell Fiorano Models

### PR DESCRIPTION
**Pull request by alexVinarskis**
I have attempted to submit directly to `linux-firmware` repo, however as per maintainer I have no authority to do so ([MR](https://gitlab.com/kernel-firmware/linux-firmware/-/merge_requests/94)).

These firmware files don't exist in Linux yet, I have extracted them from Windows driver on Dell XPS 9530 (2023), and tested on Linux with (not yet submitted) patch to CS35L51. Window's driver has more tuning files, some of which (subjectively) sound better. However, as it is unknown which tuning and when Windows uses, here are default files are per Windows's driver .inf description.

I hope as Cirrus representatives you may accept this.

### CODE REVIEW

**Comment by alexVinarskis** [comment]
@cirrus-jon kindly asking to review this PR

**Comment by stuhenderson** [comment]
Hi Alex,
Thanks for this, however please don't push around these files without permission.  These binaries aren't like open source code, and the distribution and reproduction of them are conditional on various licenses (depending on how you received the files).

The good news is that we've been testing a patch chain to improve support for laptops with insufficient DSD over the past couple of months, and hope to release this in the next week or two.  The initial patch adds various ASUS laptops, but we will push some Dell laptops (including the XPS 9530), along with appropriate firmware and tunings, once the original patch chain has been accepted upstream.

Please bear with us while we finish our internal testing.

Thanks,
Stu

**Comment by alexVinarskis** [comment]
Thank you for your review, apologies for pushing the files, I was (wrongly) under the impression it was okay.
Its great to hear that you are working on supporting these devices officially, thanks for your development!

Not sure if this is still relevant then, me and some other community members spend couple of months deriving patches to make this device work:
* Required Realtek quirk to enable amps was [already merged upstream](https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=cd14dedf15be432066e63783c63d650f2800cd48)
* Missing  _DSD data - upstream patch was [submitted](https://lore.kernel.org/all/20231212195243.10666-1-alex.vinarskis@gmail.com/)  for your review. I now assume you have a similar patch already developed internally :). Nevertheless, this solution was tested by a number of XPS 9530 users, and is now awaiting your review, we would be very glad if you could do so.

One side note about XPS 9530 specifically - as you may see in the patch linked above, XPS 9530 has an (unrelated) SPI bug due to firmware misconfiguration. It is thus required to add quirk to `intel-lpss.c` (I am working on proposing patch upstream, after initial private review by Intel developer). Without this, firmware loading to amp will take ~3minutes. In case you have/will experience the same obstacle, [here](https://github.com/thesofproject/linux/files/13618991/0001-mfd-intel-lpss-fix-clock-divider-breaking-SPI-on-XPS.txt) is the first version of `intel-lpss.c` patch (draft, will be majorly reworked before upstream submission).

Regardless, will be awaiting your internal testing, exited to get this device finally supported :)

**Comment by BuenGenio** [comment]
Really eager to hear (pun intended) how this is coming along and what the subwoofers are supposed to sound like! 
In fact, when I bought my first XPS laptop a few years ago, I didn't even realise those existed. I had just assumed they didn't bother with the sound on an otherwise beautiful machine, given how horrible the sound was on Linux, so unfortunately I parted with it. 
Just got the 2023 9530 and I'm happy it's just a driver issue. 
Wish everyone a Happy New Year!

**Comment by pioevogel** [comment]
Bump!
Very curious about the status of this.

**Comment by stuhenderson** [comment]
I believe these firmware were pushed upstream last year:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=d4b77b4fdaa3ea00bf26822f38f05fb3fe62bdff

If that's not the case, then please raise a bugzilla at the below address and CC Cirrus Patches (patches@opensource.cirrus.com) to it.
https://bugzilla.kernel.org/

Thanks.

**Comment by alexVinarskis** [comment]
@pioevogel can confirm firmware files were pushed, included from february's `linux-firmware` release

**Comment by pioevogel** [comment]
> @pioevogel can confirm firmware files were pushed, included from february's `linux-firmware` release

Thank you. I have seen firmware-updates but no changes to my Dell 9530 yet. Using Debian 12.

**Comment by alexVinarskis** [comment]
@pioevogel that is unrelated to firmware files, but to Dell's firmware bug. Fix was just merged to 6.9 mainline. More info [here](https://gist.github.com/alexVinarskis/77d55a0a0f4150576ba77e5f4241d512).

**Comment by pioevogel** [comment]
Sorry, you're right. I mixed things up.
But still great news! I'll be waiting for 6.9 then!

Thanks a lot!

**Pull request closed without merging**
